# Generated by Django 4.2.3 on 2023-07-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "bookingId",
                    models.AutoField(
                        db_column="booking_id", primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(db_column="email", max_length=70)),
                ("journeyDate", models.DateField(db_column="journey_date")),
                ("bookingDate", models.DateField(db_column="booking_date")),
                ("status", models.CharField(db_column="status", max_length=45)),
                ("pnrNumber", models.CharField(db_column="pnr_number", max_length=45)),
                (
                    "scheduleId",
                    models.CharField(db_column="schedule_id", max_length=45),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "booking_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("no_of_tickets_booked", models.IntegerField()),
                ("date", models.DateField()),
                ("available_tickets", models.IntegerField()),
                ("schedule_id", models.IntegerField()),
                ("days_left", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Seats",
            fields=[
                (
                    "seatId",
                    models.AutoField(
                        db_column="seat_id", primary_key=True, serialize=False
                    ),
                ),
                ("scheduleId", models.IntegerField(db_column="schedule_id")),
                ("seatNumber", models.CharField(db_column="seatnumber", max_length=45)),
                ("isAvailable", models.BooleanField(db_column="is_available")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transactionId",
                    models.AutoField(
                        db_column="transaction_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "transactionStatus",
                    models.CharField(db_column="transaction_status", max_length=45),
                ),
                (
                    "transactionType",
                    models.CharField(db_column="transaction_type", max_length=45),
                ),
                ("amount", models.FloatField()),
                (
                    "booking",
                    models.OneToOneField(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "passengerId",
                    models.AutoField(
                        db_column="passenger_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "passengerName",
                    models.CharField(db_column="passenger_name", max_length=45),
                ),
                ("passengerAge", models.IntegerField(db_column="passenger_age")),
                (
                    "passengerAadhar",
                    models.CharField(db_column="passenger_aadhar", max_length=45),
                ),
                (
                    "passengerStatus",
                    models.CharField(db_column="passenger_status", max_length=45),
                ),
                (
                    "seatNumber",
                    models.CharField(db_column="seat_number", max_length=45),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id_ref",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                    ),
                ),
            ],
        ),
    ]
