# Generated by Django 4.2.3 on 2023-07-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="booking", options={"managed": False},),
        migrations.AlterModelOptions(
            name="bookinghistory", options={"managed": False},
        ),
        migrations.AlterModelOptions(name="passenger", options={"managed": False},),
        migrations.AlterModelOptions(name="seats", options={"managed": False},),
        migrations.AlterModelOptions(name="transaction", options={"managed": False},),
    ]
