# Generated by Django 4.2.3 on 2023-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_options_alter_bookinghistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="booking", options={},),
        migrations.AlterModelOptions(name="bookinghistory", options={},),
        migrations.AlterModelOptions(name="passenger", options={},),
        migrations.AlterModelOptions(name="seats", options={},),
        migrations.AlterModelOptions(name="transaction", options={},),
    ]
