# Generated by Django 4.2.3 on 2023-07-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_options_alter_bookinghistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="booking", table="booking",),
        migrations.AlterModelTable(name="bookinghistory", table="booking_history",),
        migrations.AlterModelTable(name="passenger", table="passengers",),
        migrations.AlterModelTable(name="seats", table="seats",),
        migrations.AlterModelTable(name="transaction", table="transaction",),
    ]
